### ISSUE TITLE
In a compacting draw: slime balls always turn into green blocks, allowing conversion

### ISSUE THREAD

**Issue by Next-victim** [al132mc/antimatter-chemistry#47]
If you put any color slime ball in a compacting draw, it will form into green slime blocks. iIf you put in a slime ball of a different color, then put the green block into the draw: it accepts it as a block and converts it to that slime ball color.

For example: I have a 4 GREEN slime balls. When placed in a compacting draw, I can withdraw a single green slime block. If I then put a singe PINK slime ball into the draw and insert the GREEN slime block, I have the option to pull out the single pink ball AND 4 more pink balls from the block's conversion.

The photo below explains it better
![2019-05-28_03 10 09](https://user-images.githubusercontent.com/51034324/58458342-fd361180-80f6-11e9-8b7a-0caf59aa72eb.png)

**Comment by codewarrior0** [comment]
In storagedrawers.cfg, items can be blacklisted from compaction. Unsure whether green slime blocks, pink slime balls, or both ought to be blacklisted.

**Comment by al132mc** [comment]
Should be fixed in v1.2.3. Please comment if you still are having issues

**Comment by Next-victim** [comment]
Issue still occurs in 1.2.3

This included after unlocking the draws, emptying them, and filling them back up before testing.

**Comment by al132mc** [comment]
Fixed (for real this time) in 1.2.5
